version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'full-stack-ecommerce'
      MYSQL_ROOT_PASSWORD: '******'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '********'
    ports:
      - "3306:3306"
